// Autogenerated AST node
package org.apache.tajo.org.python.antlr.base;

import org.antlr.runtime.Token;
import org.apache.tajo.org.python.antlr.AST;
import org.apache.tajo.org.python.antlr.PythonTree;
import org.apache.tajo.org.python.core.PyString;
import org.apache.tajo.org.python.core.PyType;
import org.apache.tajo.org.python.expose.ExposedGet;
import org.apache.tajo.org.python.expose.ExposedType;

@ExposedType(name = "_ast.stmt", base = AST.class)
public abstract class stmt extends PythonTree {

    public static final PyType TYPE = PyType.fromClass(stmt.class);
    private final static PyString[] fields = new PyString[0];
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    public stmt() {
    }

    public stmt(PyType subType) {
    }

    public stmt(int ttype, Token token) {
        super(ttype, token);
    }

    public stmt(Token token) {
        super(token);
    }

    public stmt(PythonTree node) {
        super(node);
    }

}
