// Autogenerated AST node
package org.apache.tajo.org.python.antlr.ast;

public enum cmpopType {
    UNDEFINED,
    Eq,
    NotEq,
    Lt,
    LtE,
    Gt,
    GtE,
    Is,
    IsNot,
    In,
    NotIn;
}
