// Autogenerated AST node
package org.apache.tajo.org.python.antlr.ast;

import org.antlr.runtime.Token;
import org.apache.tajo.org.python.antlr.AST;
import org.apache.tajo.org.python.antlr.PythonTree;
import org.apache.tajo.org.python.antlr.adapter.AstAdapters;
import org.apache.tajo.org.python.antlr.base.slice;
import org.apache.tajo.org.python.core.*;
import org.apache.tajo.org.python.expose.*;

import java.util.ArrayList;

@ExposedType(name = "_ast.ExtSlice", base = AST.class)
public class ExtSlice extends slice {
public static final PyType TYPE = PyType.fromClass(ExtSlice.class);
    private java.util.List<slice> dims;
    public java.util.List<slice> getInternalDims() {
        return dims;
    }
    @ExposedGet(name = "dims")
    public PyObject getDims() {
        return new AstList(dims, AstAdapters.sliceAdapter);
    }
    @ExposedSet(name = "dims")
    public void setDims(PyObject dims) {
        this.dims = AstAdapters.py2sliceList(dims);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("dims")};
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes = new PyString[0];
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    public ExtSlice(PyType subType) {
        super(subType);
    }
    public ExtSlice() {
        this(TYPE);
    }
    @ExposedNew
    @ExposedMethod
    public void ExtSlice___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("ExtSlice", args, keywords, new String[]
            {"dims"}, 1, true);
        setDims(ap.getPyObject(0, Py.None));
    }

    public ExtSlice(PyObject dims) {
        setDims(dims);
    }

    public ExtSlice(Token token, java.util.List<slice> dims) {
        super(token);
        this.dims = dims;
        if (dims == null) {
            this.dims = new ArrayList<slice>();
        }
        for(PythonTree t : this.dims) {
            addChild(t);
        }
    }

    public ExtSlice(Integer ttype, Token token, java.util.List<slice> dims) {
        super(ttype, token);
        this.dims = dims;
        if (dims == null) {
            this.dims = new ArrayList<slice>();
        }
        for(PythonTree t : this.dims) {
            addChild(t);
        }
    }

    public ExtSlice(PythonTree tree, java.util.List<slice> dims) {
        super(tree);
        this.dims = dims;
        if (dims == null) {
            this.dims = new ArrayList<slice>();
        }
        for(PythonTree t : this.dims) {
            addChild(t);
        }
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "ExtSlice";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("ExtSlice(");
        sb.append("dims=");
        sb.append(dumpThis(dims));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitExtSlice(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (dims != null) {
            for (PythonTree t : dims) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

}
